name: Deploy to AWS S3

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to AWS S3
      uses: jakejarvis/s3-sync-action@v2
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: s3://tu-eliges-front
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: dist
